export * from './alumno';
export * from './api-error';
export * from './asistencia';
export * from './auth';
export * from './calificacion';
export * from './maestro';
export * from './materia';
export * from './pagina';
export * from './rol';
